### ISSUE TITLE
How do you use the Mac version?

### ISSUE THREAD

**Issue by Piipperi** [hareku/fanbox-dl#1]
I downloaded the latest Mac version of this tool (0.5.5), but the file downloaded has no file extension and renaming it to .app, .sh, etc still doesn't make it workable.

If you've discontinued the Mac version tho you should probably remove it from the readme

**Comment by hareku** [comment]
@Piipperi 
We haven't had Mac support for a while, but we are back. Please download and try version 0.9.1.

**Comment by hareku** [comment]
Please download from https://github.com/hareku/fanbox-dl/releases.

- Mac: `fanbox-dl_x.x.x_Darwin_x86_64`
- Mac (M1 CPU): `fanbox-dl_x.x.x_Darwin_arm64`

**Comment by Piipperi** [comment]
I did, but what now? The downloaded file has no file extension,

**Comment by hareku** [comment]
@Piipperi The file is binary and has no extension. By opening a terminal and typing `~/Downloads/fanbox-dl_x.x.x_Darwin_x86_64`, fanbox-dl will start downloading. fanbox-dl is a command line tool and does not provide any kind of graphical UI.
