### ISSUE TITLE
Download embedded images / files.

### ISSUE THREAD

**Issue by master117** [hareku/fanbox-dl#10]
Many posts now use the image / file upload / embed system provided by fanbox. It would be cool if files could be downloaded as well.

Sample post that would download nothing for me right now, because both the files and images are added as files.

https://www.fanbox.cc/@fripsite/posts/3186620

![image](https://user-images.githubusercontent.com/444009/158373326-bd239984-fbe5-4df0-a1f0-12651696b0ab.png)

Ideally I would have both the image as well as the psd file later.

**Comment by hareku** [comment]
@master117 Can you use latest version? I think fanbox-dl can download images even that are uploaded as files.
https://github.com/hareku/fanbox-dl/releases/tag/v0.14.0

**Comment by master117** [comment]
@hareku I have used the latest version. The post I linked earlier (2021-12-27) [psd] Santa Misaka by fripsite is not in my downloaded files:

![image](https://user-images.githubusercontent.com/444009/158405295-17b0e9ac-6dd3-4080-a463-70b751b99113.png)

**Comment by hareku** [comment]
@master117 Could you try once again with `--creator fripsite --all --verbose` flags, and send me logs?
`verbose` is debug flag, and `all` is for checking all posts.

**Comment by master117** [comment]
Of course, here you go :
@hareku 

[log.txt](https://github.com/hareku/fanbox-dl/files/8296334/log.txt)

There is a mention of a post called "Santa Misaka" in there, but that is not the shown post but an earlier post with normal image embed. The one we are looking for is "[psd] Santa Misaka" with these weird Japanese brackets. 

I noticed it doesn't appear in the log at all. Could it be broken because of the weird brackets? Or do they just not show up if it thinks there is no image in the post? Anyway, thank you for your help!

If you want I can donate a couple bucks so you can subscribe to this creator and check what's wrong yourself. Oh and so you can buy yourself a coffee ☕

**Comment by master117** [comment]
I just realized there is a --with-files argument I was missing. Not only does this solve my file download problems but after adding this it also downloads the image that was added as file.

Thank you very much for your effort anyway!

**Comment by dahyunnie908** [comment]
Hello, kinda stumbled to this downloader. How do I get pixiv sessid? I'm having trouble getting it. Thank you in advance!

**Comment by dahyunnie908** [comment]
I mean, can you please make a detailed steps to use this downloader? Thank you!

**Comment by master117** [comment]
> I mean, can you please make a detailed steps to use this downloader? Thank you!

Please check the readme. Also, if you have problems please open a new issue instead of posting in an existing one. Thanks.

https://github.com/hareku/fanbox-dl#--sessid-fanboxsessid

https://github.com/hareku/fanbox-dl#--sessid-fanboxsessid
