### ISSUE TITLE
Error log issue.

### ISSUE THREAD

**Issue by vneue** [hareku/fanbox-dl#15]
when i drag my exe into the command prompt window, it says
[fanbox-dl] 2022/04/01 18:42:41 [INFO] Launching Pixiv FANBOX Downloader!
[fanbox-dl] 2022/04/01 18:42:41 [INFO] Fanbox SessionID is not set. Starting as a guest.
2022/04/01 18:42:41 ===== ERROR LOG =====
2022/04/01 18:42:41 fanbox-dl failed to run: failed to resolve creator IDs: failed to list supporintg plans: status is 401 Unauthorized
2022/04/01 18:42:41 =====================
2022/04/01 18:42:41 The error log seems a bug, please open an issue on GitHub: https://github.com/hareku/fanbox-dl/issues.
how do i fix this, what am i doing wrong?

**Comment by hareku** [comment]
@vneue If you don't use `--creator` flag, fanbox-dl try to get following creators.
But you are starting as guest, so fanbox-dl failed.

See README to pass fanbox login state to fanbox-dl.
https://github.com/hareku/fanbox-dl#--sessid-fanboxsessid

**Comment by vneue** [comment]
So how do I type it.. sorry.. everything is so confusing..

**Comment by REALDoG123** [comment]
to pass fanbox login state to fanbox-dl,and i've read  README and found the cookies,but how to use it on the fanbox-dl.

**Comment by andinh1123** [comment]
im in this trouble too, i cant see the solving. How to deal w it?
