### ISSUE TITLE
[Feature Request] Output log of external hoster download links

### ISSUE THREAD

**Issue by theshillito** [hareku/fanbox-dl#18]
This may be out of scope, but there are a number of Fanbox artists I support who provide higher resolution versions of images/videos on an external hoster such as Dropbox or Mega, etc rather than using Fanbox's file hosting directly. Of course, fanbox-dl doesn't attempt to download these and I don't think it should attempt to due to the myriad hosting websites having different ways to download. However, I do think it would be helpful if a log file of some sort could be generated with a list of download links (grouped by artist probably) which I could then visit individually or provide to an external download manager (perhaps automatically if the log file is machine readable).

The links are within the `<article>` of the Fanbox post, so it should just be a case of scanning the text for any links, discarding ones for Twitter, Discord, Fanbox itself, etc, then saving them to a txt file.

As I say, this may not be functionality you wish to add, but I would really appreciate it if you did. Thank you.

**Comment by hareku** [comment]
Thank you for your feedback. We will not implement that feature due to development and maintenance reasons.
