### ISSUE TITLE
how to get fanbox id fanboxsessionied?

### ISSUE THREAD

**Issue by Tejasvmohan** [hareku/fanbox-dl#19]

**Comment by KataiKi** [comment]
In Chrome:
• Open the Developer panel (F12 on your Keyboard)
• In the top half, there's a set of tabs.  Navigate to the Application tab.
• Left Panel should have a section called Storage.  Click Cookies > https://www.fanbox.cc
• Right panel has a list of cookies under NAME | VALUE.  Copy the VALUE of the FANBOXSESSID
