### ISSUE TITLE
Binary not executing on Mac

### ISSUE THREAD

**Issue by lionbro32** [hareku/fanbox-dl#27]
I am dragging and dropping the downloaded binary for Mac into Terminal but it isn't running how it should seem to be in the post.

**Comment by hareku** [comment]
@lionbro32 
Does the error occur on both [fanbox-dl_0.17.0_Darwin_arm64](https://github.com/hareku/fanbox-dl/releases/download/v0.17.0/fanbox-dl_0.17.0_Darwin_arm64) and [fanbox-dl_0.17.0_Darwin_x86_64](https://github.com/hareku/fanbox-dl/releases/download/v0.17.0/fanbox-dl_0.17.0_Darwin_x86_64)?
