### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by DasKindaCringe** [hareku/fanbox-dl#28]
I'm sorry to bother you guys but I'm incredibly new to these coding stuff. What exactly am I supposed to do? What I did was I opened the command line interpreter (Command Prompt), and then opened the downloaded file which in my case was 'fanbox-dl_0.17.0_Windows_x86_64' but nothing happens except it saying "Fanbox SessionID is not set. Starting as a guest." and then immediately closed itself. I'm sorry for being dumb and I'd be incredibly grateful if you guys lend a hand. Thanks for your time!

**Comment by MeltryllisUsr** [comment]
Download the exe (don't bother trying to run it on its own, it doesn't work)
Put the exe in a folder name of your choice (mine is fanbox-dl)
Rename the exe to fanbox-dl.exe (just for ease of use_
Open command prompt
Type: "C:\Users\(Insert user name here)\Downloads\fanbox-dl\fanbox-dl.exe" --sessid (insert session id here) --creator (insert creator name here) --dir-by-post --save-dir "C:\Users\(Insert user name here)\Downloads\fanbox-dl"

This will automatically add the folder (insert creator name here) into the fanbox-dl folder, and begin to download the files into it.

I hope this helps other people confused on how to use this.
