### ISSUE TITLE
How to setup network proxy?

### ISSUE THREAD

**Issue by crskycode** [hareku/fanbox-dl#30]
Set environment HTTP_PROXY seems not works.

**Comment by hareku** [comment]
What is the purpose?

**Comment by crskycode** [comment]
> What is the purpose?

I want use a proxy server to make download faster.

**Comment by hareku** [comment]
I think HTTP_PROXY is supported by this lib.
https://github.com/hashicorp/go-cleanhttp/blob/02f12f05b908335f65f124c1a7f1ec45f5c42a35/cleanhttp.go#L28

Please check the format of the URL.
https://pkg.go.dev/net/http#ProxyFromEnvironment

**Comment by crskycode** [comment]
> I think HTTP_PROXY is supported by this lib. https://github.com/hashicorp/go-cleanhttp/blob/02f12f05b908335f65f124c1a7f1ec45f5c42a35/cleanhttp.go#L28
> 
> Please check the format of the URL. https://pkg.go.dev/net/http#ProxyFromEnvironment

Tested on Windows 10 and it doesn't work ( Git works ).

```
set HTTP_PROXY=http://127.0.0.1:9999
fanbox-dl // doesn't work
git clone // works
```

**Comment by crskycode** [comment]
The issue has now been solved.

![20240310043550](https://github.com/hareku/fanbox-dl/assets/21205962/391856a1-f1a6-4b7c-8a1a-f511f592c145)

So I'll need to set both `HTTP_PROXY` and `HTTPS_PROXY`

```
set HTTP_PROXY=http://127.0.0.1:9999
set HTTPS_PROXY=http://127.0.0.1:9999
```

Thanks for creating this nice tool!
