### ISSUE TITLE
Connected host has failed to respond...

### ISSUE THREAD

**Issue by templartassadar** [hareku/fanbox-dl#31]
![image](https://github.com/hareku/fanbox-dl/assets/164649707/4f28c118-9ffd-4142-b793-6a87eee9783c)
I can visit fanbox, but cannot download.
I'm sure the creator name is correct.
The SESSID is from below and I think it's also correct:
![未标题-1](https://github.com/hareku/fanbox-dl/assets/164649707/ddd6a7e0-2bad-4b52-8f26-322b358a9f96)

**Comment by hareku** [comment]
It appears that the connection at the TCP level is being denied. It is possible that some security tool on your PC is running.
Try closing the security tool or running Powershell as administrator and execute fanbox-dl.
