### ISSUE TITLE
Download File Only

### ISSUE THREAD

**Issue by SlavyanDesu** [hareku/fanbox-dl#33]
Hello. Is there any way to download the embedded file only?
Because the artist that I'm supporting only post the preview on the image section and the 'real thing' on the embedded file.
Thanks in advance.
![image](https://github.com/hareku/fanbox-dl/assets/28254882/8bbeb8e6-13a8-4565-bb6d-5ccb7da1c72b)

**Comment by Moderpach** [comment]
I also want this

**Comment by hareku** [comment]
`v0.26.1` now provides `--skip-images` flag to download files only.

**Comment by Moderpach** [comment]
thanks, love your work
