### ISSUE TITLE
fanbox listCreator api limit param max is 300

### ISSUE THREAD

**Issue by xiao-e-yun** [hareku/fanbox-dl#34]
can we change default `listCreator` limit param to 300?
or over 50 will be crash easy?

https://github.com/hareku/fanbox-dl/blob/24a4e87718549472abecfcd9cdb1c71e89fef090/pkg/fanbox/client.go#L25-L31

**Comment by hareku** [comment]
fanbox-dl retrieves all following or supporting creators using pagination, and I don't think changing `limit` value will make anything faster.

**Comment by xiao-e-yun** [comment]
Oh, okay
