### ISSUE TITLE
Images without a download link in the form of https://downloads.fanbox.cc/images/post/<postid>/<filename>.jpeg fail

### ISSUE THREAD

**Issue by S52968** [hareku/fanbox-dl#36]
`2024/06/23 18:42:52 fanbox-dl error: failed downloading of "kopam": download error: request error (https://downloads.fanbox.cc/images/post/7885769/IyHsVlWX6FMVrxFlpRA7GvZD.jpeg): GET https://downloads.fanbox.cc/images/post/7885769/IyHsVlWX6FMVrxFlpRA7GvZD.jpeg giving up after 5 attempt(s)`

It's a public post, so you can view it. For some reason, Fanbox is unable to provide the original quality image link, only leads to "failed to thumbnailing." In the case that this happens, could you add an option to choose from aborting, skipping the image, or downloading the lower quality version (preferably with something that indicates the lower quality in the name)? Example of link to the lower quality version: https://downloads.fanbox.cc/images/post/7885769/w/1200/IyHsVlWX6FMVrxFlpRA7GvZD.jpeg

**Comment by hareku** [comment]
https://github.com/hareku/fanbox-dl/releases/tag/v0.25.0
The new version will download a thumbnail instead of unavailable(too large) original image.
