### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by Akari-senpai20** [hareku/fanbox-dl#4]
After this appears and clicking the run anyway option, it instantly vanishes... what to do?
![Screenshot (1655)](https://user-images.githubusercontent.com/93815475/140604996-442c5c91-6938-4093-8b7a-db17f4159336.png)

**Comment by hareku** [comment]
@Akari-senpai20 
fanbox-dl is a command line tool, so it doesn't work if you just clicked exe on windows.
To run it, open powershell and type e.g. `C:\User\Downloads\fanbox-dl\fanbox-dl.exe --sessid yoursessionid`.
