### ISSUE TITLE
I can't open the file

### ISSUE THREAD

**Issue by Novicent** [hareku/fanbox-dl#41]
When I tried to run the application, it just popping-up for few miliseconds before turn off. Can you help me out why?
![Untitled](https://github.com/user-attachments/assets/29c95085-0f8b-417a-b4e5-58a27b5ac739)
I only take the picture of my screen before it's turn off on it's own.

**Comment by MH5273** [comment]
You need to run it using cmd. This is what I did:
1.  Create a folder named "fanbox-dl" in C Drive.
2.  Place the fanbox-dl_x.x.x_Windows_x86_64.exe file in the folder and rename it to fanbox-dl.exe.
3.  Open cmd and change the directory to the "fanbox-dl" folder (cd C:\fanbox-dl).
4.  Then run the fanbox-dl.exe file by typing fanbox-dl in cmd.
5.  The rest you can follow the command under usage at the GitHub code tab.
