### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by VamsiKrishnaThigulla** [hareku/fanbox-dl#42]
Command used: fanbox-dl_0.23.0_Windows_x86_64.exe --sessid xxxx --following=false --dir-by-plan --dir-by-post --all

![image](https://github.com/user-attachments/assets/2ae1cc82-45d2-41a8-8966-0be6e550aee2)

The command downloaded content from a few posts correctly, and on the next post, I got that error.

Retrying the command seems to download the failed image. But I can observe the later error (request failed) as well with unexpected EOF.

![image](https://github.com/user-attachments/assets/84fb1fa6-9174-4663-a7f1-efc85087d89d)

Seeing that error a few times.
For additional info, the posts here are ones containing png images.

**Comment by hareku** [comment]
@VamsiKrishnaThigulla 

Thank you for reporting.
The new version [v0.23.1](https://github.com/hareku/fanbox-dl/releases/tag/v0.23.1) retries downloading when ErrUnexpectedEOF.
