### ISSUE TITLE
Error when trying to run downloader

### ISSUE THREAD

**Issue by srctredien** [hareku/fanbox-dl#43]
Running on command `./fanbox-dl --sessid $SESSID --following=false --dir-by-post --all`

There seems to be an error parsing the response from the server, is there a way to see the error or the content of the json responses? Verbose just shows the requests.

All requests fail with `json decoding error: json: cannot unmarshal array into Go struct field ListCreatorResponse.body of type fanbox.ListCreatorResponseBody`

![Screenshot 2024-08-11 193541](https://github.com/user-attachments/assets/8478d271-3f5a-4f7a-81c1-f278c6b2794f)

Image is easier than.

**Comment by hareku** [comment]
@srctredien 
Please use the latest version. Related https://github.com/hareku/fanbox-dl/issues/40.
