### ISSUE TITLE
Fanbox downloader immediately closes upon startup

### ISSUE THREAD

**Issue by Bianca7967** [hareku/fanbox-dl#45]
![Screenshot_2808](https://github.com/user-attachments/assets/e4994048-96e9-4e28-871e-335ece81bf54)
This is as far as it goes before the command prompt suddenly closes. Any idea why?

**Comment by Jawaraisen** [comment]
Forgot it, Just Copy and paste in the Command prompt

**Comment by MH5273** [comment]
You need to run it using cmd. This is what I did:

1. Create a folder named "fanbox-dl" in C Drive.
2. Place the fanbox-dl_x.x.x_Windows_x86_64.exe file in the folder and rename it to fanbox-dl.exe.
3. Open cmd and change the directory to the "fanbox-dl" folder (cd C:\fanbox-dl).
4. Then run the fanbox-dl.exe file by typing fanbox-dl in cmd.
5. The rest you can follow the command under usage at the GitHub code tab.

**Comment by MH5273** [comment]
You need to run it using cmd. This is what I did:

1. Create a folder named "fanbox-dl" in C Drive.
2. Place the fanbox-dl_x.x.x_Windows_x86_64.exe file in the folder and rename it to fanbox-dl.exe.
3. Open cmd and change the directory to the "fanbox-dl" folder (cd C:\fanbox-dl).
4. Then run the fanbox-dl.exe file by typing fanbox-dl in cmd.
5. The rest you can follow the command under usage at the GitHub code tab.
