### ISSUE TITLE
Get Pagination: Status is 404 not found

### ISSUE THREAD

**Issue by VamsiKrishnaThigulla** [hareku/fanbox-dl#48]
![image](https://github.com/user-attachments/assets/945ec76c-2d9b-4cf0-9e99-0c2a867e9f7f)

Seeing above error, retrying gives the same.

**Comment by VamsiKrishnaThigulla** [comment]
Is there any way to add a skip or something, that will continue the download and skip the current post/user if there's an error as shown above? Thanks.

**Comment by hareku** [comment]
The error means that the creator name does not exist.
