### ISSUE TITLE
Failed downloading: Download with retry

### ISSUE THREAD

**Issue by VamsiKrishnaThigulla** [hareku/fanbox-dl#49]
When trying to download from a single creator, I'm seeing the following:
![image](https://github.com/user-attachments/assets/0f477546-574d-470a-9cf7-cb7feeadadb7)

**Comment by VamsiKrishnaThigulla** [comment]
Is there any way to add a skip or something, that will continue the download and skip the current post if there's an error as shown above? Thanks.

**Comment by hareku** [comment]
https://github.com/hareku/fanbox-dl/releases/tag/v0.24.0 provides `skip-on-error` flag.
