### ISSUE TITLE
[Feature Request] Downloading of attached files

### ISSUE THREAD

**Issue by Melanpan** [hareku/fanbox-dl#5]
Been using fanbox-dl for a while now to automatically download any new creator I follow, but I recently noticed that some creators attach a file, or multiple files, to their post, and it would be really neat if fanbox-dl could grab these as well!

![firefox_ks2NnEL3Qu](https://user-images.githubusercontent.com/12272837/144818115-d83eee58-b677-4cc5-a13c-71bcb93dca2e.png)

**Comment by hareku** [comment]
@Melanpan 

File downloading feature has been released in `v0.12.0`.
If you want to download files (not images), add `--with-files` flag.
