### ISSUE TITLE
Error 400 Bad Request

### ISSUE THREAD

**Issue by MH5273** [hareku/fanbox-dl#51]
![Screenshot 2024-10-27 070718](https://github.com/user-attachments/assets/7770d0e5-39ce-4f21-965b-5884e6c4ea26)

I have this error when running the "fanbox-dl_0.24.0_Windows_x86_64.exe" on cmd with and without VPN.

**Comment by 01101sam** [comment]
1. `--sessid` **or** `--cookie`, can't use both
2. Add your Cloudflare clearance cookie too

**Comment by MH5273** [comment]
The problem is I'm just executing the downloaded fanbox-dl binary. I'm not even starting anything yet. Not even adding --sessid or --cookie.

**Comment by mb534** [comment]
fanbox-dl is supposed to be executed as a single command with all relevant arguments. See the [example in the README](https://github.com/hareku/fanbox-dl?tab=readme-ov-file#example).

**Comment by 01101sam** [comment]
fanbox has Cloudflare protection, please try to access <fanbox.cc> using browser, then open DevTools -> Application, find Cookies, expend tab and get the fanbox url, copy __cf_bm and clearance cookie, the add --cookie "cf_bm=...;clearance=..." as args

Note: IP and binary has to be the same for cookies to work together

**Comment by MH5273** [comment]
Can you give me an example of a full command to download all the materials (pictures and videos) from Fanbox? I don't understand how to use them. What does it mean by IP and binary has to be the same?

**Comment by 01101sam** [comment]
> Can you give me an example of a full command to download all the materials (pictures and videos) from Fanbox? What if I want to download the materials from a certain period of time (from date A to date B)? I don't understand how to use them. What does it mean by IP and binary has to be the same?

First, Copilot is available for you to ask those question. Try to use them to ask about command related question.

About the `IP and binary has to be the same`, Fanbox has enabled [cloudflare challenge #39](https://github.com/hareku/fanbox-dl/issues/39), therefore you should only use [--cookie option with --user-agent provided](https://github.com/hareku/fanbox-dl/issues/39#issuecomment-2211700096). If still occur problem, try enabling VPN to JP as well.
I assume your IP didn't restricted, but failed entering `--cookie` and `--user-agent`.

Here's an example command, fill in the `...` with your own data.

`./fanbox-dl --cookie "FANBOXSESSID=...;__cf_bm=...;cf_clearance=...;p_ab_d_id=...;p_ab_id=6;p_ab_id_2=7;privacy_policy_agreement=7;privacy_policy_notification=0" --user-agent "..." --dry-run`

This command won't download files, after you ensure you can run and see any `Skipping` logs, you can then remove `--dry-run` option.

**Comment by zako890016** [comment]
I am Japanese, but when I change the example to my own and run it, I get a 401 error!

**Comment by 01101sam** [comment]
> I am Japanese, but when I change the example to my own and run it, I get a 401 error!

Are you sure your both Cookies were provided correctly?
If yes, and if you confirm your IP can access Fanbox directly from browser but can't access using this tool, try to copy all cookies from browser.

If you're using on a virtual machine (VM), please make sure your IP is still the same when you access the fanbox website.
If not, please find a way to access via VM's IP (For example, opening a HTTP / SOCKS proxy on VM, then use browser extension to accees this proxy to gain Cookies) 

Kinda complex, please try to follow the instructions yourself.

**Comment by zako890016** [comment]
Sorry, I guess it came up because I wasn't logged into my fanbox account, I'm so sorry!

**Comment by 01101sam** [comment]
> Sorry, I guess it came up because I wasn't logged into my fanbox account, I'm so sorry!

:rofl: it's okey

**Comment by zako890016** [comment]
I'm going off topic here, but if I'm not on a paid plan, will I be able to download the images for that plan?

**Comment by 01101sam** [comment]
> I'm going off topic here, but if I'm not on a paid plan, will I be able to download the images for that plan?

You can only download the images that you already subscribed / sponsored for.
