### ISSUE TITLE
Failed downloading: check whether does image exist: stat file: CreateFile : The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by VamsiKrishnaThigulla** [hareku/fanbox-dl#54]
Version 0.25.0
Having the following issue:
![image](https://github.com/user-attachments/assets/ce96ca86-fd08-4276-b527-0c6af111d473)

"failed downloading of \"tikuwazyousyou\": check whether does image exist: stat file: CreateFile images\\tikuwazyousyou\\500yen\\2024-10-06-【skeb】\t104 高画質＋フェチ向けイラスト、差分など計１３枚\\0-LE07vFqMsXPy7ItVDl9Wjdt5.jpeg: The filename, directory name, or volume label syntax is incorrect."

I've tried to remove the dir options, and it still errors out.
I've also used the skip-on-error flag, but it still exits at this error.
I've also checked the directory specified, and there is no file with such a name (the file exists on the original post).

The result is the same even after removing the --all flag.

Question: Is there a way to set a filename flag i.e. 0th image is simply named 0.jpeg instead of 0-xxxxx.jpg?

**Comment by mb534** [comment]
I'm trying to replicate this error on my machines, but haven't yet. Were there any successful downloads before that one? Assuming you're on Windows, what system locale are you set to ([example of how to check on Windows 11](https://geekrewind.com/how-to-change-system-locale-in-windows-11/))? Is the behaviour the same with the most recent fanbox-dl release?

I guess the `--skip-on-error` flag needs broadening to catch this kind of problem too. I may raise a PR.

I think there is not currently a way to set the filename format as you wish, apart from the predefined "dir-by" flags.

**Comment by VamsiKrishnaThigulla** [comment]
I used the latest version to run the command again (v 0.26.2). 3 posts and the images in them got downloaded without issues. After encountering the problematic post, it exited with the same error message.

System locale is English (United States).

![image](https://github.com/user-attachments/assets/adaa9722-7489-4bc9-b756-440a2863ad9d)

Also, it's specifically this creator alone (and probably that specific post alone) where I'm observing the issue so far, for the other creators I'm supporting, I was able to download without any exit after using the --skip-on-error flag.

**Comment by hareku** [comment]
The new version `v0.27.0` provides `--remove-unprintable-chars` flag to remove unprintable characters from file names for some environments.

> The proposed solution linked there seems to resolve this problem, and was committed to this repo, but then [reverted](https://github.com/hareku/fanbox-dl/commit/74985e7200d5fd9cdc7bb021220579e90aaaef1d) for some reason.

I reverted this change as it broke backwards compatibility in some environments.
