### ISSUE TITLE
Failed Download with command string

### ISSUE THREAD

**Issue by notKarb** [hareku/fanbox-dl#55]
I use this command line (my sessid is filled in with my own)
PS F:\Fanbox Downloader> .\fanbox-dl --sessid xxx --save-dir ./content --creator @noil-poisoncat --all

and I get this error: 

time=2024-10-31T23:39:45.075Z level=INFO msg="Launching Pixiv FANBOX Downloader!" version=0.25.0 commit=276f7bb9936a6989a324caa60f8accdc35d24ab3 date=2024-10-31T04:32:30Z
time=2024-10-31T23:39:45.076Z level=INFO msg="Start downloading" creator_id=@noil-poisoncat
time=2024-10-31T23:39:45.241Z level=ERROR msg="fanbox-dl Error" error="failed downloading of \"@noil-poisoncat\": get pagination: status is 403 Forbidden"
time=2024-10-31T23:39:45.241Z level=ERROR msg="The error log seems a bug, please open an issue on GitHub" url=https://github.com/hareku/fanbox-dl/issues
PS F:\Fanbox Downloader>

**Comment by hareku** [comment]
Related https://github.com/hareku/fanbox-dl/issues/39#issuecomment-2450235481

**Comment by notKarb** [comment]
I tried a VPN and this didn't fix the issue
