### ISSUE TITLE
[Feature Requests and Questions]About Already Downloaded

### ISSUE THREAD

**Issue by yumilus** [hareku/fanbox-dl#56]
Is there a database function that manages the downloaded list so that when downloads are automatically run in a batch file, posts that have already been downloaded are not downloaded again? If not, can it be added?

Is it possible to add a function to notify users by email or other means when a download fails (authentication error)?

I need this to create a system that automatically saves the posts of my favorite artists.

**Comment by mb534** [comment]
> Is there a database function that manages the downloaded list so that when downloads are automatically run in a batch file, posts that have already been downloaded are not downloaded again? If not, can it be added?

Yes, this is the default behaviour. The `--all` flag also ensures that the program doesn't terminate as soon as it encounters a file which is already downloaded. It doesn't actually download everything again.

> Is it possible to add a function to notify users by email or other means when a download fails (authentication error)?

It's possible to script the sending of emails on command-line on Linux or Windows, so couldn't you integrate one of those tools into a script? Although, fanbox-dl currently returns the usual code 0 when it exits with errors logged, so it should really return a non-zero code in that case. I will raise a PR for that.

**Comment by yumilus** [comment]
Thanks, I thought the --all flag was supposed to re-download everything every time. Now I can use the --all flag without any worries!

I have created a script in ChatGPT that sends an email with the error details when an error occurs in a Python script.
This is not based on the error code, but rather the console output at download time is logged to a log file, and if the log file contains an ERROR after execution, the line is emailed to the user.

Translated with DeepL.com (free version)

**Comment by hareku** [comment]
Next version exits with code 1 when the command failed.
