### ISSUE TITLE
Pinned Posts prevents detection of other posts publicated later

### ISSUE THREAD

**Issue by Diatorker** [hareku/fanbox-dl#58]
Steps to reproduce :
* chose a creator that have a pinned post a download all the posts
* remove some posts publicated after the publication date of the pinned post
* update the creator posts again
* fanbox-dl will stop without finding the missing posts

it seems that pinned posts are returned first if your try to download all posts from scratch. Maybe it messes the recognition of new posts?

**Comment by hareku** [comment]
https://github.com/hareku/fanbox-dl/releases/tag/v0.27.1
The new version will check the latest post even old posts are pinned to the top.
