### ISSUE TITLE
Issue with computer or this exe file?

### ISSUE THREAD

**Issue by minecraftkiller006** [hareku/fanbox-dl#6]
I downloaded the right version of the latest release .exe file. I then ran it as administrator, but nothing really happened. Is there supposed to be a pop-up? Or does it just install files elsewhere.

**Comment by poison696** [comment]
same for me

**Comment by hareku** [comment]
You have to run `fanbox-dl` from a command line interpreter.
Please see updated readme https://github.com/hareku/fanbox-dl#usage
