### ISSUE TITLE
File downloading appears to be broken

### ISSUE THREAD

**Issue by matrix07012** [hareku/fanbox-dl#7]
I tried versions 0.12, 0.12.1, 12.2 on Windows and all of them seem to be ignoring attachments without any error

EDIT: I just tried a different creator and it's working. Maybe the issue is videos? The creator not working is oda1ga.

**Comment by hareku** [comment]
@matrix07012 
Thank you for your bug reporting!

This bug has been fixed, and we released a new version. Please check it out.
https://github.com/hareku/fanbox-dl/releases/tag/v0.13.0
