### ISSUE TITLE
Download videos 

### ISSUE THREAD

**Issue by OkayuHanekawa** [hareku/fanbox-dl#8]
--with-files
I cant download videos made for subscriptions.

Like this one for example. 
https://rux-work.fanbox.cc/posts/1581111
I. Cant download. I wish that could be a feature to download the video wichout payng or subscribing @hareku @BeatButton #5 

![Screenshot_2022-02-05-10-45-04-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/99053816/152635008-4e6db148-b1f1-4449-ad08-3de9f1c911d6.jpg)

**Comment by hareku** [comment]
@OkayuHanekawa 
Please make sure you are using `--with-files` flag for fanbox-dl command.

**Comment by hareku** [comment]
@OkayuHanekawa
you mean... without paying? Of course you can't. That's a crime literally.
